feat: Marcacao Servico
tskxz/ElectroFix pull request #63
Opened 2024-12-05 22:32 UTC by RicardoMaga

2024-12-05 22:37 UTC, tskxz requested changes
Na página de agendar, só está a mostrar o endereço, devia mostrar mais informações como por exemplo nome do cliente, email e número de telemóvel

2024-12-05 22:39 UTC, tskxz requested changes

2024-12-05 22:39 UTC, tskxz commented on frontend/src/Screens/AgendarServicoScreen/AgendarServicoScreen.jsx
> +									${carrinho.precoEnvio}
```suggestion
									20.00€
```

2024-12-06 10:41 UTC, tskxz approved these changes

2024-12-06 10:43 UTC, tskxz reviewed
Adicionou-se um slice novo no redux
![image](https://github.com/user-attachments/assets/0c2fce9a-9d2b-4dd0-a2f0-1fb018313abf)

2024-12-06 10:44 UTC, tskxz commented on frontend/src/Screens/AgendarServicoScreen/AgendarServicoScreen.jsx
> +									{agenda.enderecoPostal.dataMarcacao}
E em vez de ser no slice carrinho, pegamos as informações através do slice agenda

2024-12-06 10:57 UTC, tskxz reviewed
Adicionou se precoDeslocalemento, precoTaxa e precoTotal
![image](https://github.com/user-attachments/assets/d4e5477e-9575-41e9-b3cb-d0d79918a0e4)

2024-12-06 11:39 UTC, tskxz reviewed
Criou se o agendaModel e criamos  a api para criar uma agenda
![image](https://github.com/user-attachments/assets/2f3e34aa-a549-41a8-9185-24c2438afb9f)

2024-12-06 11:40 UTC, tskxz commented on frontend/src/Screens/AgendarServicoScreen/AgendarServicoScreen.jsx
> +		}
Ao clicar no botão agendar, vai ser chamado a função agendarHandler, que vai usar a api que criou se no backend, para criar uma nova agenda e vai armazenar na base de dados

2024-12-06 11:57 UTC, tskxz reviewed
Criou se uma nova página para ver os detalhes da agenda
![image](https://github.com/user-attachments/assets/c83e1067-4bb8-4cf5-853d-bdc6c6ed18ad)

É preciso ainda fazer algumas mudanças

2024-12-06 12:28 UTC, tskxz reviewed
Adicionou se para ver as agendas que o cliente fez
![image](https://github.com/user-attachments/assets/e03f1593-6d10-41c0-b05d-3daf8cb3afda)

2024-12-06 12:33 UTC, tskxz reviewed
Após o pagamento, vai atualizar o campo agenda.isPago para true
![image](https://github.com/user-attachments/assets/ba8915a8-e61a-436d-bd9e-ac98a578e88a)

2024-12-06 12:41 UTC, tskxz requested changes
Na página /agendar deve incluir as informações do utilizador na parte de dados pessoais
@RicardoMaga

Isso pode ser feito ao pegar as informações do utilizador com:

```js
const {utilizadorInfo} = useSelector((state) => state.auth)
```

 Para mostrar, {utilizadorInfo.nome}
 
![image](https://github.com/user-attachments/assets/b0d56e89-e91e-475c-bc3c-7dffaa176841)

2024-12-06 22:07 UTC, RicardoMaga commented on backend/controllers/agendaController.js
> +// @desc    Ter agfendas efetuadas pelo utilizador
"Ter agfendas" corrigir isto meu menino

2024-12-06 22:40 UTC, tskxz commented on backend/controllers/agendaController.js
> +// @desc    Ter agfendas efetuadas pelo utilizador
Corrige tu

2024-12-06 22:44 UTC, tskxz requested changes

2024-12-06 22:44 UTC, tskxz commented on backend/controllers/agendaController.js
> +// @desc    Ter agfendas efetuadas pelo utilizador
```suggestion
// @desc    Ter agendas efetuadas pelo utilizador
```

2024-12-06 22:48 UTC, RicardoMaga commented on backend/controllers/agendaController.js
> +// @desc    Ter agfendas efetuadas pelo utilizador
```suggestion
// @desc    Ter agendas efetuadas pelo utilizador
```

2024-12-10 14:34 UTC, tskxz approved these changes

2024-12-10 14:34 UTC, merged